[package]
name = "data_structs_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
fasthash = "0.4.0"

[lib]
name = "data_structures"
path = "src/lib.rs"
